"""Task storage helpers for the local Polos runtime."""

from __future__ import annotations

import re
import uuid
from pathlib import Path

from polos.audit.reader import read_jsonl
from polos.contracts.task import TaskContract, utc_now
from polos.runtime.environment import write_environment_profile


TASK_ROOT = Path(".agent") / "tasks"
TASK_ARTIFACTS = {
    "task": "TASK.yaml",
    "plan": "PLAN.md",
    "log": "LOG.md",
    "toolcalls": "TOOLCALLS.jsonl",
    "evidence": "EVIDENCE.md",
    "review": "REVIEW.md",
}


def init_runtime(root: Path, force: bool = False) -> list[Path]:
    agent_root = root / ".agent"
    tasks_root = agent_root / "tasks"
    audit_root = agent_root / "audit"
    environment_root = agent_root / "environment"
    created: list[Path] = []
    for directory in (agent_root, tasks_root, audit_root, environment_root):
        directory.mkdir(parents=True, exist_ok=True)
        created.append(directory)
    readme = agent_root / "README.md"
    if force or not readme.exists():
        readme.write_text(
            "# Polos Runtime State\n\n"
            "This directory is generated by the local Polos runtime. It stores task contracts, "
            "audit references, verification evidence, and loop ledgers. Do not store secrets here.\n",
            encoding="utf-8",
        )
        created.append(readme)
    profile = write_environment_profile(root, force=force)
    created.append(profile)
    return created


def create_task(
    root: Path,
    original_request: str,
    title: str | None = None,
    autonomy_level: str = "L2",
    risk_level: str = "low",
    requested_mode: str = "plan",
) -> TaskContract:
    init_runtime(root)
    task_title = title or derive_title(original_request)
    task_id = new_task_id(task_title)
    task_path = root / TASK_ROOT / task_id
    artifacts = dict(TASK_ARTIFACTS)
    contract = TaskContract(
        task_id=task_id,
        title=task_title,
        original_user_request=original_request,
        normalized_goal=normalize_goal(original_request),
        intent_ref=f"intent:{task_id}",
        acceptance_criteria=["A reviewed plan exists before any effectful tool execution."],
        risk_level=risk_level,
        autonomy_level=autonomy_level,
        requested_mode=requested_mode,
        permissions={
            "planning_tools": [],
            "execution_tools": [],
            "network": "deny",
            "secrets": "deny",
        },
        budgets={
            "max_iterations": 1,
            "max_wall_clock_seconds": 0,
            "max_cost_usd": 0,
        },
        required_checks=["mesh_validate"],
        created_at=utc_now(),
        status="planned",
        artifacts=artifacts,
        path=task_path,
    )
    contract.write()
    write_artifacts(contract)
    return contract


def list_tasks(root: Path) -> list[TaskContract]:
    tasks_root = root / TASK_ROOT
    if not tasks_root.exists():
        return []
    tasks: list[TaskContract] = []
    for path in sorted(tasks_root.iterdir()):
        if path.is_dir() and (path / "TASK.yaml").exists():
            tasks.append(TaskContract.load(path))
    return tasks


def load_task(root: Path, task_id: str) -> TaskContract:
    path = root / TASK_ROOT / task_id
    if not (path / "TASK.yaml").exists():
        raise FileNotFoundError(f"task not found: {task_id}")
    return TaskContract.load(path)


def select_task(root: Path, task_id: str | None = None) -> TaskContract:
    if task_id:
        return load_task(root, task_id)
    tasks = list_tasks(root)
    if not tasks:
        raise FileNotFoundError("no task records found; run `polos plan \"...\"` first")
    return tasks[-1]


def update_task_status(task: TaskContract, status: str) -> None:
    task.status = status
    task.write()
    log_path = task.path / "LOG.md"
    with log_path.open("a", encoding="utf-8") as handle:
        handle.write(f"\n- {utc_now()} status -> {status}\n")


def read_toolcalls(task: TaskContract) -> list[dict[str, object]]:
    return read_jsonl(task.path / "TOOLCALLS.jsonl")


def write_artifacts(contract: TaskContract) -> None:
    plan = contract.path / "PLAN.md"
    if not plan.exists():
        plan.write_text(
            f"# {contract.title}\n\n"
            "## Goal\n"
            f"{contract.normalized_goal}\n\n"
            "## Authority Boundary\n"
            "Planning is recorded here. Effectful execution requires an Execution Worker grant.\n",
            encoding="utf-8",
        )
    for artifact in ("LOG.md", "EVIDENCE.md", "REVIEW.md"):
        path = contract.path / artifact
        if not path.exists():
            path.write_text(f"# {artifact.removesuffix('.md').title()}\n", encoding="utf-8")
    toolcalls = contract.path / "TOOLCALLS.jsonl"
    if not toolcalls.exists():
        toolcalls.write_text("", encoding="utf-8")


def derive_title(request: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", request)[:8]
    return " ".join(words) or "Untitled task"


def normalize_goal(request: str) -> str:
    return " ".join(request.strip().split())


def new_task_id(title: str) -> str:
    slug = "-".join(re.findall(r"[a-z0-9]+", title.lower()))[:48] or "task"
    return f"{utc_now().replace(':', '').replace('-', '').lower()}-{slug}-{uuid.uuid4().hex[:8]}"
